#ifndef __CC1120_H__
#define __CC1120_H__

typedef enum _CC1120_COMM_CMD {
	COMM_JOINT = 1,
	COMM_SCAN,
	COMM_UNJOINT,
	COMM_INFO,
	COMM_SYNC,
	COMM_ADD,
	COMM_QUERY,

	COMM_JOINT_RPL = 0x81,
	COMM_SCAN_RPL,
	COMM_UNJOINT_RPL,
	COMM_INFO_RPL,
	COMM_SYNC_RPL,
	COMM_ADD_RPL,
	COMM_QUERY_RPL,

	COMM_SEND_IR = 0x11,
	COMM_VALUES_GET,
	COMM_ADE_GET,
	COMM_ADE_SET,
	COMM_UTILS_SET,
	
	COMM_GW_TO_TH = 0x41,
	
	COMM_SEND_IR_RPL = 0x91,
	COMM_VALUES_RPL,
	COMM_ADE_GET_RPL,
	COMM_ADE_SET_RPL,
	COMM_UTILS_RPL,
	
	COMM_TH_TO_GW = 0xC1,
	
} CC1120_COMM_CMD;

#endif //#ifndef __CC1120_H__
